title: Receitas do Dia
tagline:
logo:
description: >-
baseurl: /public_html/homolog8/receitasdodia
url: http://leadmedia.com.br
lang: pt-br
theme: minima
author:
  - name: Lucas Sales
    url: http://github.com/LucasBortolini
plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript
sass:
  sourcemap: never
postcss:
  cache: false
collections:
  pages:
    output: true